nameOverride: ""
fullnameOverride: ""

missionControl:
  db:
    runMigrations: true
    storageClass: managed
  flanksource-ui:
    oryKratosURL: https://mission-control.local/kratos
    ingress:
      annotations:
        kubernetes.io/tls-acme: "true"
      host: mission-control.local
      tls:
        - hosts:
            - mission-control.demo.local
          secretName: mission-control-tls

vcluster:
  sync:
    ingresses:
      enabled: true
  storage:
    size: 15Gi
  init:
    manifests: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: production
