nameOverride: ""
fullnameOverride: ""
domain: ""
missionControlChartVersion: ">=0.0.0"
tenantSlug: ""
telemetryPushURL: https://telemetry.app.flanksource.com/push/topology
missionControl:
  authProvider: clerk
  clerkJWKSURL: ""
  clerkOrgID: ""
  global:
    ui:
      host: app.flanksource.com
    labels:
      flanksource.com/clerk-org-id: ""
    otel:
      collector: grafana-alloy.mission-control:4317
  serviceAccount:
    rbac:
      impersonate: true
  db:
    create: false
  flanksource-ui:
    enabled: false
  apm-hub:
    enabled: false
  kratos:
    enabled: false
  properties:
    log.kubeproxy: "true"
    incidents.disable: "true"
    logs.disable: "true"
    settings.logging_backends.disable: "true"

k8sRegistry:
  clusterName: kubernetes-hosted-saas
  topology:
    enabled: false

# See https://github.com/loft-sh/vcluster/blob/main/charts/k3s/values.yaml
vcluster:
  plugin:
    sync-host-secrets:
      image: docker.io/flanksource/vcluster-sync-host-secrets:v0.1.6
      env:
      - name: DESTINATION_NAMESPACE
        value: mission-control

  sync:
    secrets:
      all: true
    ingresses:
      enabled: true
  storage:
    size: 15Gi

  # Map grafana agent host service to mission-control namespace in tenant to push traces
  mapServices:
    fromHost:
      - from: monitoring/grafana-alloy
        to: mission-control/grafana-alloy
