nameOverride: ""
fullnameOverride: ""
domain: ""
missionControlChartVersion: ">=0.0.0"
missionControl:
  canary-checker:
    db:
      runMigrations: true
      storageClass: managed
  flanksource-ui:
    oryKratosURL: https://mission-control.local/api/.ory
    ingress:
      enabled: false

# See https://github.com/loft-sh/vcluster/blob/main/charts/k3s/values.yaml
vcluster:
  plugin:
    sync-host-secrets:
      image: docker.io/flanksource/vcluster-sync-host-secrets:v0.1.6
  sync:
    secrets:
      all: true
    ingresses:
      enabled: true
  storage:
    size: 15Gi
