nameOverride: ""
fullnameOverride: ""
domain: ""
missionControlChartVersion: ">=0.0.0"
tenantSlug: ""
telemetryPushURL: https://telemetry.app.flanksource.com/push/topology
missionControl:
  authProvider: clerk
  clerkJWKSURL: ""
  clerkOrgID: ""
  global:
    labels:
      flanksource.com/clerk-org-id: ''
    otel:
      collector: grafana-agent-traces.default:4317
  db:
    create: false
  flanksource-ui:
    enabled: false
  apm-hub:
    enabled: false
  kratos:
    enabled: false
  properties:
    incidents.disable: 'true'
    logs.disable: 'true'
    settings.logging_backends.disable: 'true'

# See https://github.com/loft-sh/vcluster/blob/main/charts/k3s/values.yaml
vcluster:
  plugin:
    sync-host-secrets:
      image: docker.io/flanksource/vcluster-sync-host-secrets:v0.1.6
  sync:
    secrets:
      all: true
    ingresses:
      enabled: true
  storage:
    size: 15Gi

  # Map grafana agent host service to default namespace in tenant to push traces
  mapServices:
    fromHost:
      - from: monitoring/grafana-agent-traces
        to: default/grafana-agent-traces
