nameOverride: ""
fullnameOverride: ""

missionControl:
  canary-checker:
    db:
      runMigrations: true
      storageClass: managed
  flanksource-ui:
    oryKratosURL: https://mission-control.local/api/.ory
    ingress:
      annotations:
        kubernetes.io/tls-acme: "true"
      host: mission-control.local
      tls:
        - hosts:
            - mission-control.demo.local
          secretName: mission-control-tls

# See https://github.com/loft-sh/vcluster/blob/main/charts/k3s/values.yaml
vcluster:
  plugin:
    sync-host-secrets:
      image: docker.io/flanksource/vcluster-sync-host-secrets:v0.1.4
  sync:
    secrets:
      all: true
    ingresses:
      enabled: true
  storage:
    size: 15Gi
