apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ include "mission-control-tenant.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mission-control-tenant.labels" . | nindent 4 }}
spec:
  interval: 5m
  chart:
    spec:
      chart: mission-control
      version: {{ .Values.missionControlChartVersion }}
      sourceRef:
        kind: HelmRepository
        name: {{ include "mission-control-tenant.fullname" . }}
  targetNamespace: default
  storageNamespace: default
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  kubeConfig:
    secretRef:
      name: vc-{{ .Release.Name }}
      key: config
  {{- with .Values.missionControl }}
  values:
    {{- toYaml . | nindent 4 }}
  {{- end }}
