apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ include "mission-control-tenant.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mission-control-tenant.labels" . | nindent 4 }}
spec:
  interval: 5m
  chart:
    spec:
      chart: mission-control
      version: {{ .Values.missionControlChartVersion | quote }}
      sourceRef:
        kind: HelmRepository
        name: {{ include "mission-control-tenant.fullname" . }}
      interval: 1m
  targetNamespace: default
  storageNamespace: default
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  kubeConfig:
    secretRef:
      name: vc-{{ .Release.Name }}
      key: config
  {{- with .Values.missionControl }}
    {{- $global := $ }}
    {{- $customValues := dict }}

    {{- $otelDict := dict "otel" (dict "labels" (printf "org.id=%s,tenant.slug=%s" .clerkOrgID $global.Values.tenantSlug)) }}
    {{- $labelsDict := dict "labels" (dict "flanksource.com/clerk-org-id" .clerkOrgID ) }}

    {{- $globalDict := dict "global" (merge (dict "otel" (dict "labels" $otelDict.otel.labels)) $labelsDict) }}

    {{- $_ := set $customValues "global" $globalDict.global }}
    {{- $mergedValues := mergeOverwrite . $customValues }}
  values:
    {{- toYaml $mergedValues | nindent 4 }}
  {{- end }}
