{{- if eq .Values.missionControl.authProvider "clerk" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mission-control-{{.Release.Name}}
  namespace: {{.Release.Namespace}}
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: ingress-ca
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128m"
    nginx.ingress.kubernetes.io/client-body-buffer-size: "8m"
    nginx.ingress.kubernetes.io/proxy-body-size: "128m"
spec:
  ingressClassName: ingress-nginx
  rules:
  - host: {{.Values.domain | quote}}
    http:
      paths:
      - backend:
          service:
            name: mission-control-x-default-x-{{.Release.Name}}
            port:
              number: 8080
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - {{.Values.domain | quote}}
    secretName: mission-control-tls-{{.Release.Name}}

{{- else -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: incident-manager-ui-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: ingress-ca
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128m"
    nginx.ingress.kubernetes.io/client-body-buffer-size: "8m"
    nginx.ingress.kubernetes.io/proxy-body-size: "128m"
spec:
  tls:
    - hosts:
        - {{ .Values.domain | quote }}
      secretName: mission-control-tls-{{ .Release.Name }}
  ingressClassName: ingress-nginx
  rules:
    - host: {{ .Values.domain | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: incident-manager-ui-x-default-x-{{ .Release.Name }}
                port:
                  number: 80
{{- end -}}
