{{- if .Values.hostnameOverride -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: incident-manager-ui-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  tls:
    - hosts: {{ .Values.hostnameOverride | quote }}
      secretName: mission-control-tls-{{ .Release.Name }}
  rules:
    - host: {{ .Values.hostnameOverride | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: incident-manager-ui-x-default-x-{{ .Release.Name }}
                port:
                  number: 80
{{- end }}