apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ include "mission-control-tenant.fullname" . }}-kubernetes
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mission-control-tenant.labels" . | nindent 4 }}
spec:
  interval: 5m
  chart:
    spec:
      chart: mission-control-kubernetes
      version: {{ .Values.missionControlChartVersion | quote }}
      sourceRef:
        kind: HelmRepository
        name: {{ include "mission-control-tenant.fullname" . }}
      interval: 5m
  targetNamespace: mission-control
  storageNamespace: mission-control
  kubeConfig:
    secretRef:
      name: vc-{{ .Release.Name }}
      key: config
  values:
    clusterName: {{.Values.k8sRegistry.clusterName}}
    topology:
      enabled: {{.Values.k8sRegistry.topology.enabled}}
    scraper:
      exclusions:
        labels:
          app.kubernetes.io/instance: mission-control-{{ include "mission-control-tenant.fullname" . }}
