apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ include "mission-control-tenant.fullname" . }}-kubernetes
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mission-control-tenant.labels" . | nindent 4 }}
spec:
  interval: 5m
  chart:
    spec:
      chart: mission-control-kubernetes
      version: {{ .Values.missionControlChartVersion | quote }}
      sourceRef:
        kind: HelmRepository
        name: {{ include "mission-control-tenant.fullname" . }}
      interval: 5m
  targetNamespace: default
  storageNamespace: default
  kubeConfig:
    secretRef:
      name: vc-{{ .Release.Name }}
      key: config
  values:
    clusterName: kubernetes-hosted-saas
    topology:
      enabled: false
    scraper:
      exclusions:
        labels:
          app.kubernetes.io/instance: default-{{ .Release.Namespace }}-{{ include "mission-control-tenant.fullname" . }}
