---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: '{{ include "mission-control-tenant.fullname" . }}-reader-role'
rules:
  - apiGroups: ['']
    resources: ['configmaps', 'secrets']
    verbs: ['get', 'list', 'watch']
  - apiGroups:
      - 'configs.flanksource.com'
      - 'canaries.flanksource.com'
      - 'mission-control.flanksource.com'
    resources: ['*']
    verbs: ['get', 'list', 'watch']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: '{{ include "mission-control-tenant.fullname" . }}-writer-role'
rules:
  - apiGroups: ['']
    resources: ['configmaps', 'secrets']
    verbs: ['*']
  - apiGroups:
      - 'configs.flanksource.com'
      - 'canaries.flanksource.com'
      - 'mission-control.flanksource.com'
    resources: ['*']
    verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: '{{ include "mission-control-tenant.fullname" . }}-reader-rolebinding'
subjects:
  - kind: User
    name: 'mission-control-reader'
roleRef:
  kind: ClusterRole
  name: '{{ include "mission-control-tenant.fullname" . }}-reader-role'
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: '{{ include "mission-control-tenant.fullname" . }}-writer-rolebinding'
subjects:
  - kind: User
    name: 'mission-control-writer'
roleRef:
  kind: ClusterRole
  name: '{{ include "mission-control-tenant.fullname" . }}-writer-role'
  apiGroup: rbac.authorization.k8s.io
