apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: config-db-{{.Release.Name}}-monitor
spec:
  endpoints:
    - port: http
      interval: 30s
  selector:
    matchLabels:
      app.kubernetes.io/name: config-db
      vcluster.loft.sh/managed-by: "{{ .Release.Name }}"
      vcluster.loft.sh/namespace: default
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mission-control-{{ .Release.Name }}-monitor
spec:
  endpoints:
    - port: http
      interval: 30s
  selector:
    matchLabels:
      app.kubernetes.io/name: mission-control
      vcluster.loft.sh/managed-by: "{{ .Release.Name }}"
      vcluster.loft.sh/namespace: default
